#!/bin/bash

alias ll="ls -l"
alias ..="cd .."

alias subl="open -a Sublime\ Text.app"
alias md5sum="md5"

alias mysql="/usr/local/mysql/bin/mysql"
#alias mysqlcon="mysql -u root -p"
alias mysqladmin="/usr/local/mysql/bin/mysqladmin"
alias mysqldump="/usr/local/mysql/bin/mysqldump"
