#!/bin/bash

alias ll="ls -l"
alias ..="cd .."

alias subl="open -a Sublime\ Text\ 2.app"
alias md5sum="md5"

alias mysql="/usr/local/mysql/bin/mysql"
alias mysqlcon="mysql -u root -ptoor"
alias mysqladmin="/usr/local/mysql/bin/mysqladmin"
alias mysqldump="/usr/local/mysql/bin/mysqldump"
