#!/bin/bash

export EDITOR="vim"

# Set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

# Add IntelliJ IDEA command
PATH="${PATH}:/Applications/IntelliJ IDEA.app/Contents/MacOS"

# Configure Homebrew's completions
#FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

ICLOUD_PATH="${HOME}/Library/Mobile Documents/com~apple~CloudDocs"

# Add ~/bin to $PATH if exists
if [ -d ${HOME}/bin ]; then
    export PATH="${HOME}/bin:${PATH}"
fi
